version: 2

sources:
  - name: staging
    #For bigquery: # project gcp wich regroup all th datasets of of the project
    database: mszoomcamp2024
    # For postgres:
    #database: production
    # dataset
    schema: trips_data_all

    # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
        # freshness:
        # error_after: {count: 6, period: hour}
      - name: fhv_tripdata
